name: tutopedia

services:
  ###################################################
  # Service: Reverse Proxy
  ###################################################
  proxy:
    image: traefik:v2.11
    container_name: proxy
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###################################################
  # Service: database
  ###################################################
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=tutopedia_db
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      # routers
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.entryPoints=postgres"
      - "traefik.tcp.routers.postgres.service=postgres"
      # services (needed for TCP)
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  liquibase:
    image: liquibase
    container_name: liquibase
    volumes:
      - /Users/rudiwelter/Workdir/Tut-O-Pedia/Backend/src/main/resources/db/:/db/
    depends_on:
      postgres:
        condition: service_healthy
    command: --url=jdbc:postgresql://postgres:5432/tutopedia_db --search-path=/db/ --changeLogFile=db.changelog-master.xml --username=postgres --password=admin update

  ###################################################
  # Service: backend
  ###################################################
  backend:
    image: rwdevops999/topbackend
    container_name: backend
    environment:
      - db_user=postgres
      - db_password=admin
      - db_host=postgres
      - db_port=5432
      - db_database=tutopedia_db
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 8081

  ###################################################
  # Service: frontend
  ###################################################
  frontend:
    image: rwdevops999/topfrontend
    container_name: frontend
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5173

volumes:
  postgres:
